# Generated by Django 5.1.7 on 2025-08-07 23:56

import apps.health.models.hydration
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Força', 'Força'), ('Flexibilidade', 'Flexibilidade'), ('Aeróbico', 'Aeróbico'), ('Resistência', 'Resistência')], max_length=20)),
                ('is_distance', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='Mindfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Respiração Consciente', 'Respiração Consciente'), ('Meditação Mindfulness', 'Meditação Mindfulness'), ('Consciência Emocional', 'Consciência Emocional'), ('Atenção nas Atividades', 'Atenção nas Atividades')], max_length=22)),
            ],
            options={
                'verbose_name': 'Mindfulness',
                'verbose_name_plural': 'Mindfulness',
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Exercircio',
                'verbose_name_plural': 'Registros de Exercircio',
            },
        ),
        migrations.CreateModel(
            name='HydrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(default=apps.health.models.hydration.HydrationLog.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hydration',
                'verbose_name_plural': 'Hydration',
            },
        ),
        migrations.CreateModel(
            name='MindfulnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=200)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('mindfulness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.mindfulness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mindfulness Log',
                'verbose_name_plural': 'Mindfulness Logs',
            },
        ),
    ]
