# Generated by Django 5.1.7 on 2025-11-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='distance',
        ),
    ]
