# Generated by Django 5.1.7 on 2025-11-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_exerciselog_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mindfulnesslog',
            name='description',
        ),
    ]
