# Generated by Django 5.1.7 on 2025-08-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_steplog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steplog',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='steplog',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='steplog',
            name='calories',
        ),
    ]
