# Generated by Django 5.1.7 on 2025-07-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_objective_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='deadline',
        ),
        migrations.AddField(
            model_name='objective',
            name='reminder',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='repeat',
            field=models.CharField(choices=[('1x', '1 Vez'), ('3x', '2 Vezes'), ('5x', '3 Vezes')], default='1x', max_length=2),
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
