# Generated by Django 5.1.7 on 2025-07-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_remove_objective_deadline_objective_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='best_streak',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
