# Generated by Django 5.1.7 on 2025-08-07 23:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('mood', models.CharField(choices=[('Excelente', 'Excelente'), ('Bom', 'Bom'), ('Neutro', 'Neutro'), ('Ruim', 'Ruim'), ('Péssimo', 'Péssimo')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='diary/photos/')),
                ('activities', models.ManyToManyField(blank=True, to='diary.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diário',
                'verbose_name_plural': 'Diários',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1w', '1 semana'), ('2w', '2 semanas'), ('3w', '3 semanas')], default='1w', max_length=2)),
                ('repeat', models.CharField(choices=[('1x', '1 Vez'), ('3x', '2 Vezes'), ('5x', '3 Vezes')], default='1x', max_length=2)),
                ('reminder', models.TimeField(blank=True, null=True)),
                ('best_streak', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
            },
        ),
    ]
