# Generated by Django 5.1.7 on 2025-11-27 20:03

import django.db.models.deletion
import django.utils.timezone
import utils.validate_type_img
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(auto_now_add=True)),
                ('mood', models.CharField(choices=[('Excelente', 'Excelente'), ('Bom', 'Bom'), ('Neutro', 'Neutro'), ('Ruim', 'Ruim'), ('Péssimo', 'Péssimo')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='diary/photos/', validators=[utils.validate_type_img.validate_image_type])),
                ('activities', models.ManyToManyField(blank=True, to='diary.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diário',
                'verbose_name_plural': 'Diários',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='diary_diary_user_id_09cf5a_idx'), models.Index(fields=['mood'], name='diary_diary_mood_2ce7fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.CharField(choices=[('1x', '1 Vez'), ('3x', '2 Vezes'), ('5x', '3 Vezes')], default='1x', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='diary_objec_user_id_464b53_idx'), models.Index(fields=['activity'], name='diary_objec_activit_8d00a4_idx')],
            },
        ),
    ]
