# Generated by Django 5.1.7 on 2025-08-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='reminder',
        ),
    ]
