# Generated by Django 5.1.7 on 2025-10-29 01:42

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_objective_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ('-created_at',), 'verbose_name': 'Diário', 'verbose_name_plural': 'Diários'},
        ),
        migrations.RemoveField(
            model_name='diary',
            name='datetime',
        ),
        migrations.AddField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['user', 'created_at'], name='diary_diary_user_id_09cf5a_idx'),
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['mood'], name='diary_diary_mood_2ce7fd_idx'),
        ),
    ]
