# Generated by Django 5.1.7 on 2025-10-30 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_options_remove_diary_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ('-created_at',), 'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivos'},
        ),
        migrations.RemoveField(
            model_name='objective',
            name='best_streak',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='period',
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['user', 'created_at'], name='diary_objec_user_id_464b53_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['activity'], name='diary_objec_activit_8d00a4_idx'),
        ),
    ]
