# Generated by Django 5.1.7 on 2025-11-01 02:26

import utils.validate_type_img
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_objective_options_remove_objective_best_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='diary/photos/', validators=[utils.validate_type_img.validate_image_type]),
        ),
    ]
