# Generated by Django 5.1.7 on 2025-10-24 15:38

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievementlevel',
            name='condition',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='achievementlevel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievementlevel',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Facil'), (2, 'Intermediario'), (3, 'Dificil')]),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
                ('content', models.CharField(max_length=256)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('HD', 'Hydration'), ('EX', 'Exercise'), ('MD', 'Mindfulness'), ('DR', 'Diary'), ('OT', 'Others')], max_length=2)),
                ('is_daily', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
            },
        ),
    ]
