# Generated by Django 5.1.7 on 2025-11-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_alter_achievement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hydration_goal',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='steps_goal',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
