# Generated by Django 5.1.7 on 2025-11-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_hydration_goal_user_steps_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
