# Generated by Django 5.1.7 on 2025-11-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_reminder_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='deadline',
        ),
    ]
